host: :8081
api:
  match_service_flag: "matchService"
database:
    addr: "bitaksi-geopoint.dbi34.mongodb.net"
    port: 27017
    username: selahattinceylan
    password: bitaksideneme
    dataPath: ""